#!/bin/bash

action=$1
target=$2
dir=$3
name=$4

case $action in
    new)
        case $target in
            rscript)
                rscript $dir $name
                ;;
            project)
                createProject $dir $name
                ;;
            *)
                echo "Failed"
                ;;
        esac
        ;;
    *)
        echo "Only option 'new' supported currently..."
        ;;
esac

